### ISSUE TITLE
Character spacing too wide.

### ISSUE THREAD

**Issue by ghost** [adobe-fonts/source-han-code-jp#14]
Character spacing is too wide When use it with GNOME Terminal.
Can you please fix it?

**Comment by hatchzo** [comment]
I could not fixed it. Some terminal to cording apps in Windows seems to require the monospace bit in a font setting to handle glyph spacing. Source Han Code JP does not have this bit because monospace glyphs are only Latin, it does not have the exact same spacing all through glyphs. Even if give this bit to this kind of font, these apps don't handle glyph spacing as expected.

**Comment by kenlunde** [comment]
I am planning to address this issue in the Pan-CJK version of this typeface.
