### ISSUE TITLE
Support Source Code Pro ITALICS?

### ISSUE THREAD

**Issue by zchee** [adobe-fonts/source-han-code-jp#5]
Hi, 
Thanks great Japanese program font.

`Source Code Pro` font has released compatible Italic type font.
But, `Source Han Code` is not supported.

Is  it possible to extend the support to [Source Code Pro ITALICS](https://github.com/adobe-fonts/source-code-pro/releases/tag/1.003-it)?
Or, Please tell me how to make (cidfont.ps, ciddnfo, feature, table.BASE and table.vmtx](https://github.com/adobe-fonts/source-han-code-jp/tree/master/Bold).

Thanks.
# 

`Source Code Pro`はベータとしてイタリック体をサポートしています。
しかし、`Source Han Code` はサポートしていないように思います。

[Source Code Pro ITALICS](https://github.com/adobe-fonts/source-code-pro/releases/tag/1.003-it)をサポートする予定はありますか？
または、ベースとなっている`Source Code Pro`と`Source Han Sans`から[cidfont.ps, ciddnfo, feature, table.BASE,table.vmtx](https://github.com/adobe-fonts/source-han-code-jp/tree/master/Bold)の生成方法を教えて頂きたいです。

**Comment by kenlunde** [comment]
Due to the way in which Source Han Code JP is derived from Source Han Sans, in that it retains the CIDs from the original 65,535-glyph glyph set, building an italic version is not as easy as one would think.

Of course, it would be possible to build Source Han Code JP Italic as separate font resources, but all of the non-Latin glyphs would be the same as the non-italic version, which represents a lot of wasted space.

It is also possible to include the italic glyphs using different CIDs and using the 'ital' GSUB feature, but that would require forking the glyph set, which would make it difficult to extend Source Han Code to support other languages, and the 'ital' GSUB feature is not broadly supported.

**Comment by kenlunde** [comment]
If you want to do this on your own, it would be useful for @hatchzo to include in the README.md file the steps for converting the Source Code Pro glyphs into a form that was used in Source Han Code JP, to include a list of what CIDs were replaced, and a mapping table from Source Code Pro glyph names to Source Han Code JP CIDs (so that the AFDKO _mergeFonts_ can be used to easily insert the italic glyphs).

**Comment by zchee** [comment]
Thanks reply.
I understand.
It is quite difficult :(

>  @hatchzo to include in the README.md file the steps for converting the Source Code Pro glyphs into a form that was used in Source Han Code JP, to include a list of what CIDs were replaced, and a mapping table from Source Code Pro glyph names to Source Han Code JP CIDs (so that the AFDKO mergeFonts can be used to easily insert the italic glyphs).

Yes, Please tell me how to make.
I'm waiting for @hatchzo 's reply.

BTW, I have another question so I will post the issue.

**Comment by hatchzo** [comment]
I am just curious to make Source Han Code JP Italic, because I don't know Japanese mono-space font which  supports italic latin glyphs. But I can't guarantee anything about making the font.

**Comment by ShikiSuen** [comment]
You could use FontForge to make it by yourself. They are all CID fonts.
You simply open a font and replace its Latin part with all glyphs come from Source Code Pro Italic.

**Comment by hatchzo** [comment]
Now, Roman Italic is available in Source Han Code JP v2.000.
